### ISSUE TITLE
Cannot make it work API error

### ISSUE THREAD

**Issue by valentinfage** [johnbryanmoore/VL53L0X_rasp_python#10]
Can't run any python scripts, this is what I get when i'm trying to launch python VL53L0X_example.py or any other (livegraph and so on...) on my Raspberry.

VL53L0X Start Ranging Object 0 Address 0x29

Call of VL53L0X_DataInit
API Status: -20 : Control Interface Error
Timing 20 ms
Call of VL53L0X_StopMeasurement
API Status: -20 : Control Interface Error
Any idea why? Thanks

**Comment by miguelpom** [comment]
Hello,

Sorry to comment again in this closed issue. I am currently experiencing this same problem.
@valentinfage , did you find a solution? 
Did anyone?

One thing I notice trying to make the VL53L0X work is that after executing: `sudo i2cdetect -y 1` on the terminal no device is detected.

I wound really appreciate some help with this, or at least some clue to where to start investigating.

Thank you in advance.

**Comment by miguelpom** [comment]
Hi, again.

So... guess what. I solve the issue myself. Actually, it was kind of a stupid thing.
I just needed to pay attention to what the VL53L0X datasheet says about its pins. 
In my case I use a Pololu VL53L0X sernsor and apart form this difference, the Fritzing schematic in this repository doesn't tell you much about the function of the "XSHUT" pin (or equivalent).
As it turns out, that pin works as some kind of "ON/OFF" switch for the sensor: 
- pin at HIGH level = sensor ON 
- pin at LOW level = sensor OFF

If you just leave the pin connected to an unused GPIO in the Raspberry Pi, the sensor might read it as being at low level ordering the sensor to remain inactive. To check if I was right about this, I connected the "XSHUT" pin to one of the 3V3 pins in the Raspberry Pi and it worked just fine.

Hope this may help anyone else. And remember, read your documentation twice or thrice before you start whining online.

Best regards! (and apologies for my grammar)
